services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    image: python:3.10
    container_name: AutoMecabPython3.10
    hostname: AutoMecabDocker
    volumes:
      - ../:/workspace
    tty: true